<?php
session_start();
require_once __DIR__ . '/../config/db.php';

// Authentication Guard: Admin access required
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../auth/login.php");
    exit;
}

// Date Range Filtering Parameters
$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date   = $_GET['end_date'] ?? date('Y-m-t');

// 1. Fetch Financial Summary
$stmt_summary = $pdo->prepare("
    SELECT 
        COUNT(id) AS total_orders,
        COALESCE(SUM(total_price), 0) AS total_revenue,
        COALESCE(AVG(total_price), 0) AS avg_order_value
    FROM orders 
    WHERE DATE(created_at) BETWEEN ? AND ?
");
$stmt_summary->execute([$start_date, $end_date]);
$summary = $stmt_summary->fetch();

// 2. Fetch Top Selling Products
$stmt_top = $pdo->prepare("
    SELECT m.name, SUM(oi.quantity) AS total_qty, SUM(oi.quantity * oi.price) AS total_sales
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.id
    JOIN menu_items m ON oi.item_id = m.id
    WHERE DATE(o.created_at) BETWEEN ? AND ?
    GROUP BY m.id, m.name
    ORDER BY total_qty DESC
    LIMIT 5
");
$stmt_top->execute([$start_date, $end_date]);
$top_items = $stmt_top->fetchAll();

// 3. Fetch Full Orders Breakdown
$stmt_orders = $pdo->prepare("
    SELECT o.* 
    FROM orders o
    WHERE DATE(o.created_at) BETWEEN ? AND ?
    ORDER BY o.created_at ASC
");
$stmt_orders->execute([$start_date, $end_date]);
$orders = $stmt_orders->fetchAll();

$page_title = "Sales_Report_" . $start_date . "_to_" . $end_date;
$hide_navbar = true;
$body_class = 'pdf-body';
require_once __DIR__ . '/../includes/header.php';
?>

<!-- Printable Floating Toolbar -->
<div class="no-print-bar bg-dark text-white p-3 d-print-none sticky-top shadow d-flex justify-content-between align-items-center">
    <div class="small">
        <i class="bi bi-file-earmark-pdf me-1 text-danger"></i>
        <strong>PDF Executive Sales Report Preview</strong> &nbsp;|&nbsp;
        <span class="text-secondary">Period: <?= htmlspecialchars($start_date) ?> to <?= htmlspecialchars($end_date) ?></span>
    </div>
    <div class="d-flex gap-2">
        <button onclick="window.print()" class="btn btn-primary btn-sm fw-bold">
            <i class="bi bi-printer me-1"></i> Print / Save as PDF
        </button>
        <a href="index.php?start_date=<?= urlencode($start_date) ?>&end_date=<?= urlencode($end_date) ?>" class="btn btn-secondary btn-sm">
            Close Preview
        </a>
    </div>
</div>

<!-- Printable PDF Sheet Container -->
<div class="container my-4 printable-sheet">
    <div class="card border border-secondary-subtle shadow-sm rounded-3 p-4 p-md-5 bg-white">
        <!-- Header Table -->
        <div class="d-flex justify-content-between align-items-start border-bottom border-2 border-dark pb-3 mb-4">
            <div>
                <h2 class="fw-bold text-dark mb-0">🍔 Yum's berchg</h2>
                <p class="text-muted text-uppercase extra-small fw-semibold mb-0">Executive Sales & Financial Revenue Report</p>
            </div>
            <div class="text-end extra-small text-secondary">
                <div><strong>Report ID:</strong> RPT-<?= date('Ymd-His') ?></div>
                <div><strong>Generated On:</strong> <?= date('F j, Y - g:i A') ?></div>
                <div><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['username'] ?? 'Administrator') ?></div>
            </div>
        </div>

        <!-- Period Badge -->
        <div class="badge bg-info-subtle text-info-emphasis border border-info-subtle px-3 py-2 rounded-2 mb-4">
            <i class="bi bi-calendar3 me-1"></i> Reporting Period: <strong><?= date('F j, Y', strtotime($start_date)) ?></strong> &mdash; <strong><?= date('F j, Y', strtotime($end_date)) ?></strong>
        </div>

        <!-- Financial Summary Grid -->
        <div class="row row-cols-3 g-3 text-center mb-4">
            <div class="col">
                <div class="border rounded-3 p-3 bg-light">
                    <span class="extra-small text-uppercase text-muted fw-bold">Gross Revenue</span>
                    <div class="fs-4 fw-bold text-success mt-1">₱<?= number_format($summary['total_revenue'], 2) ?></div>
                </div>
            </div>
            <div class="col">
                <div class="border rounded-3 p-3 bg-light">
                    <span class="extra-small text-uppercase text-muted fw-bold">Orders Completed</span>
                    <div class="fs-4 fw-bold text-primary mt-1"><?= number_format($summary['total_orders']) ?></div>
                </div>
            </div>
            <div class="col">
                <div class="border rounded-3 p-3 bg-light">
                    <span class="extra-small text-uppercase text-muted fw-bold">Average Order Value</span>
                    <div class="fs-4 fw-bold text-info mt-1">₱<?= number_format($summary['avg_order_value'], 2) ?></div>
                </div>
            </div>
        </div>

        <!-- Section 1: Top Selling Items -->
        <h6 class="fw-bold text-uppercase text-dark border-bottom pb-2 mb-3">1. Top Selling Menu Items</h6>
        <?php if (empty($top_items)): ?>
            <p class="small text-muted mb-4">No menu items sold during this period.</p>
        <?php else: ?>
            <table class="table table-bordered table-sm align-middle small mb-4">
                <thead class="table-dark">
                    <tr>
                        <th class="text-center" style="width: 60px;">Rank</th>
                        <th>Menu Item Name</th>
                        <th class="text-center">Quantity Sold</th>
                        <th class="text-end">Total Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $rank = 1; foreach ($top_items as $item): ?>
                        <tr>
                            <td class="text-center fw-bold">#<?= $rank++ ?></td>
                            <td class="fw-bold"><?= htmlspecialchars($item['name']) ?></td>
                            <td class="text-center"><?= number_format($item['total_qty']) ?> pcs</td>
                            <td class="text-end text-success fw-bold">₱<?= number_format($item['total_sales'], 2) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>

        <!-- Section 2: Order Transactions Ledger -->
        <h6 class="fw-bold text-uppercase text-dark border-bottom pb-2 mb-3">2. Order Transactions Ledger</h6>
        <?php if (empty($orders)): ?>
            <p class="small text-muted mb-4">No order records found for this reporting window.</p>
        <?php else: ?>
            <table class="table table-bordered table-striped table-sm align-middle small mb-4">
                <thead class="table-dark">
                    <tr>
                        <th>Order #</th>
                        <th>Date & Time</th>
                        <th>Customer Name</th>
                        <th>Phone</th>
                        <th>Delivery Address</th>
                        <th class="text-end">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $grand_total = 0; foreach ($orders as $order): $grand_total += $order['total_price']; ?>
                        <tr>
                            <td class="fw-bold">#<?= $order['id'] ?></td>
                            <td><?= date('Y-m-d H:i', strtotime($order['created_at'])) ?></td>
                            <td class="fw-bold"><?= htmlspecialchars($order['customer_name']) ?></td>
                            <td><?= htmlspecialchars($order['phone']) ?></td>
                            <td><?= htmlspecialchars($order['address']) ?></td>
                            <td class="text-end fw-bold text-dark">₱<?= number_format($order['total_price'], 2) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr class="table-secondary fw-bold">
                        <td colspan="5" class="text-end text-uppercase">Grand Total Revenue:</td>
                        <td class="text-end text-success fs-6">₱<?= number_format($grand_total, 2) ?></td>
                    </tr>
                </tbody>
            </table>
        <?php endif; ?>

        <!-- Document Footer -->
        <div class="d-flex justify-content-between pt-3 border-top border-dashed extra-small text-muted">
            <div>Yum's berchg &copy; <?= date('Y') ?> &bull; Confidential Financial Report</div>
            <div>Generated via Yum's berchg Management System</div>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
